### ISSUE TITLE
one question

### ISSUE THREAD

**Issue by Wbqqqq** [ChiliLabs/CHIPageControl#11]
when i used CHIPageControlJalapeno class to  make cycleSrollerview demo , i found a bug.
For example ,  i have four images ,   when  the fourth img back to  first  image ， i used    `self.pageControl.progress = progress;`  the animation pause for a moment   like this  picture。
![Uploading 0D790545-B2D8-43F1-9863-FCC86BFF5385.png…]()

**Comment by Wbqqqq** [comment]
![0d790545-b2d8-43f1-9863-fcc86bff5385](https://cloud.githubusercontent.com/assets/17332298/24190244/0a7e31f8-0f23-11e7-9fa3-8a1d4bdea91b.png)

**Comment by Wbqqqq** [comment]
if add back animation ,i think this code will be better

**Comment by chili-ios** [comment]
hi @Wbqqqq , thanks for bug report. We will investigate it.

**Comment by chili-ios** [comment]
@Wbqqqq, please update to version 0.0.5
