### ISSUE TITLE
CHIPageControlFresno layout is broken？

### ISSUE THREAD

**Issue by cm-kato-jun** [ChiliLabs/CHIPageControl#13]
When I use `set(progress:animated:)` method, the layout of the `CHIPageControlFresno` is broken ?
↓Here is my company tech blog about CHIPageControl.
http://dev.classmethod.jp/smartphone/chipagecontrol/

**Comment by cm-kato-jun** [comment]
![fresno](https://cloud.githubusercontent.com/assets/14919491/24234983/646728c6-0fde-11e7-8c3b-c4f3705b6d69.png)

**Comment by chili-ios** [comment]
hi @cm-kato-jun, great blog post, it's more detailed than our Readme 👍 
Have you checked the latest version 0.0.5? Does the issue still exist?

**Comment by cm-kato-jun** [comment]
Hi！😃 
Today, I checked the latest version `0.0.5`. but the issue still exist.

**Comment by chili-ios** [comment]
thanks for checking, will fix it asap!

**Comment by mihailstumkins** [comment]
Hi @cm-kato-jun  
this problem is fixed in the 0.0.6 version which is the latest currently

**Comment by cm-kato-jun** [comment]
@mihailstumkins Thanks！💯
