### ISSUE TITLE
animation not working

### ISSUE THREAD

**Issue by canaksoy** [ChiliLabs/CHIPageControl#16]
`override func viewDidLoad() {
        super.viewDidLoad()
        
        splashScrollView.contentSize = CGSize(width: screenSize.width*4, height: screenSize.height)
        splashScrollView.isPagingEnabled = true
        splashScrollView.delegate = self
        self.view.addSubview(splashScrollView)
        
        pageControl = CHIPageControlAji(frame: CGRect(x: (screenSize.width/2)-100, y: screenSize.height-90, width: 200, height: 20))
        pageControl.numberOfPages = 4
        pageControl.radius = 4
        pageControl.tintColor = colorWhite
        pageControl.padding = 6
        self.view.addSubview(pageControl)
        
        self.view.setNeedsUpdateConstraints()
    }
    func scrollViewDidEndDecelerating(_ scrollView: UIScrollView) {
        
        if (scrollView == splashScrollView) {
            
            let total = scrollView.contentSize.width - scrollView.bounds.width
            let offset = scrollView.contentOffset.x
            let percent = Double(offset / total)
            
            let progress = percent * Double(4 - 1)
            pageControl.set(progress: Int(progress), animated: true)
            
        }
    }`

**Comment by canaksoy** [comment]
but `pageControl.progress = progress` is working

**Comment by chili-ios** [comment]
@canaksoy, thanks for the bug report. Will be fixed today.

**Comment by chili-ios** [comment]
@canaksoy please try version 0.1.1
