### ISSUE TITLE
Updating the number of pages does not redraw

### ISSUE THREAD

**Issue by mauropiccini** [ChiliLabs/CHIPageControl#18]
Changing the number of pages with
`self.pageControl.numberOfPages = newNum`

as result the old drawing is not cleared
<img width="247" alt="screen shot 2017-03-29 at 13 34 57" src="https://cloud.githubusercontent.com/assets/907926/24452683/a978a174-1484-11e7-8260-6181858a7b48.png">

Mauro.

**Comment by chili-ios** [comment]
hi @mauropiccini, thanks for bug report.
Which page control are you using?

**Comment by chili-ios** [comment]
@mauropiccini please try new version 0.1.1

**Comment by mauropiccini** [comment]
Yeah, it works!
Sorry I didn't check for an update first.
