### ISSUE TITLE
[!] Unable to find a specification for `CHIPageControl (~> 0.0.1)`

### ISSUE THREAD

**Issue by otymartin** [ChiliLabs/CHIPageControl#2]
[!] Unable to find a specification for `CHIPageControl (~> 0.0.1)`

I get this error when trying to install the pod

@jstart @love4soul

**Comment by chili-ios** [comment]
@otymartin seems like it's a problem with your CocoaPods specs file. Try to do `pod update` or something from this [topic](http://stackoverflow.com/a/32850706/2182641).

**Comment by otymartin** [comment]
@chili-ios I updated my cocoapods version and it worked.
Thanks

**Comment by chili-ios** [comment]
@otymartin cool :)
