### ISSUE TITLE
It cannot work in latest Xcode

### ISSUE THREAD

**Issue by CaptainYukinoshitaHachiman** [ChiliLabs/CHIPageControl#21]

**Comment by CaptainYukinoshitaHachiman** [comment]
<img width="1602" alt="screen shot 2017-04-08 at 3 27 43 am" src="https://cloud.githubusercontent.com/assets/25654046/24816720/5b506470-1c0c-11e7-884c-3953363c20b5.png">

**Comment by chili-ios** [comment]
hi @CaptainYukinoshitaHachiman, 

Really strange, I just opened Example project in xCode 8.3.1 and it seems to work as expected. 
Can you please double check that everything is installed correctly? Make sure that you set a `Module` in storyboard to be `CHIPageControl` if you are using cocoapods.

**Comment by chili-ios** [comment]
closing it because of no response. If the issue still exists, please re-open.

**Comment by Rool** [comment]
Thanks @chili-ios , setting `Module` to `CHIPageControl` for the element in Interface Builder fixed my runtime error.
