### ISSUE TITLE
CHIPageControlAji throws exception when numberOfPages = 1 and progress = 0

### ISSUE THREAD

**Issue by lazybetrayer** [ChiliLabs/CHIPageControl#24]
When `numberOfPages = 1` and `progress = 0`, `func update(for progress: Double)` throws exception: `CALayerInvalidGeometryCALayer, position contains NaN: [nan 0]`.

**Comment by chili-ios** [comment]
@lazybetrayer thanks for bug report. Please check new version 0.1.3
