### ISSUE TITLE
Active page out of bounds

### ISSUE THREAD

**Issue by stasivanov** [ChiliLabs/CHIPageControl#28]
Is it possible to handle big number of pages, so active indicator will be always visible?

In case width of control is less than required by the number of pages, then active indicator keeps moving out of bounds. 

I would tell that it should handle this case, and if active indicator is "near" bounds, then it should move all unactive indicators to the left/right, and active indicator should have static positions.

**Comment by chili-ios** [comment]
hi @stasivanov , we have no plans to add this kind of a feature, but PR is welcome 👍
