### ISSUE TITLE
CHIPageControlAji inactive background

### ISSUE THREAD

**Issue by ChristRm** [ChiliLabs/CHIPageControl#29]
Its impossible to set background color for CHIPageControlAji, I tried to achieve this using cornerRadius but active circle in this case is always smaller than inactive and dont overlap it

**Comment by mihailstumkins** [comment]
@ChristRm 

Hi.
Could you please describe more, what are you trying to achieve? 
Would be awesome if you could provide screenshots as well.

**Comment by chili-ios** [comment]
closing it for now
