### ISSUE TITLE
CHIPageControl Active Element Frame 

### ISSUE THREAD

**Issue by mkaya93** [ChiliLabs/CHIPageControl#31]
Hi,

Is there any chance to use 2 different frame for page controls. For example I'm using CHIPageControlJaloro And I want to use different width for current element.

Also I Know there is a variable which name is active in CHIPageControlJaloro. But we can't access it outside of pod.

**Comment by mkaya93** [comment]
Anything ? @love4soul

**Comment by love4soul** [comment]
hi @mkaya93 ,

can you please attach an example how you want it to look like?

**Comment by mkaya93** [comment]
hi @love4soul,
It's needs to look like this. 

![screen shot 2017-07-07 at 16 18 13](https://user-images.githubusercontent.com/6665723/27959392-e9d5b668-632f-11e7-9042-bb5a28d245cd.png)

**Comment by mkaya93** [comment]
Hi @love4soul, 

I added an image for example. 
![screen shot 2017-07-12 at 10 36 58](https://user-images.githubusercontent.com/6665723/28106813-0fe944e8-66ee-11e7-8bd6-983fbaa8804b.png)

**Comment by love4soul** [comment]
hi @mkaya93 ,
Unfortunately, CHIPageControlJaloro doesn't work like that. Active element is always displayed on top and only x position is changed. Event if active element's frame is public it will not be able to get such an effect, as inactive elements should relayout according to active element position and width.
