### ISSUE TITLE
How to change the alpha of the inactive indicators ?

### ISSUE THREAD

**Issue by Mohammed-Eliass** [ChiliLabs/CHIPageControl#32]
The alpha of the inactive indicators is too much, is there any way to reduce it ?

**Comment by chili-ios** [comment]
hi @Mohammed-Eliass ,
Use `.inactiveTransparency` for that. It can be changed in code or in Interface builder.

**Comment by Mohammed-Eliass** [comment]
Thanks for this awesome library !
Apparently the min is 0, Could you please tell me the max of this value?

**Comment by chili-ios** [comment]
you are welcome :)

Value of `.inactiveTransparency` should be in range 0 - 1, default is 0.4.

**Comment by Mohammed-Eliass** [comment]
I think there's a problem in the IB, took a look please !

![screen shot 2017-07-24 at 3 34 29 pm](https://user-images.githubusercontent.com/18654470/28523544-a24f279e-7085-11e7-88e0-b81f532ed767.png)

**Comment by chili-ios** [comment]
try to enter 0,2 (or 0.2) manually

**Comment by Mohammed-Eliass** [comment]
Nothing happened 
> pageControl.tintColor = .yellow
> pageControl.currentPageTintColor = .yellow
> pageControl.inactiveTransparency = 0.2
Then I got this photo :( , even in the IB I removed everything and leave it empty
![screen shot 2017-07-24 at 4 11 57 pm](https://user-images.githubusercontent.com/18654470/28524848-d8dd9994-708a-11e7-8e30-c1625966cca1.png)

**Comment by chili-ios** [comment]
Please check this gif - https://gyazo.com/74c491cb743e5003d4fdfee159bf2259

**Comment by Mohammed-Eliass** [comment]
same old, same old !
I gave it 0,1 .. 0,9 in IB nothing
with code 0.1 .. 0.9 the same.

**Comment by chili-ios** [comment]
have you checked the example project?

**Comment by Mohammed-Eliass** [comment]
yeah, the example works, but the version I got I newer than the example, could you please try it on your local machine (the current version) !

**Comment by chili-ios** [comment]
example can't be older, it uses same files. In podfile `pod 'CHIPageControl', :path => '../'`
Are you using cocoapods or carthage ?

**Comment by Mohammed-Eliass** [comment]
cocoapods !
I didn't get the same attributes in the interface builder !

**Comment by Mohammed-Eliass** [comment]
This's the version I'm working with, it's the same as the example project (My fault sorry) :
![screen shot 2017-07-24 at 5 08 31 pm](https://user-images.githubusercontent.com/18654470/28527362-edf7b244-7092-11e7-8917-aa896837320f.png)

**Comment by Mohammed-Eliass** [comment]
Xcode Bug everything work after restarting Xcode, your library is awesome 👍
