### ISSUE TITLE
Working on above XCode 9.2?

### ISSUE THREAD

**Issue by muthukrishnanOCS** [ChiliLabs/CHIPageControl#37]
Hello,

I am trying to integrate this POD in my Objective-C.

I am facing some issues.

we have to convert this to bridging header in XCode 8.0

Can you help me please ?

**Comment by chili-ios** [comment]
hi @muthukrishnanOCS ,
Sorry for late response. Have you solved it?

**Comment by muthukrishnanOCS** [comment]
yes @chili-ios thanks for a response

**Comment by chili-ios** [comment]
Great!
