### ISSUE TITLE
Doesn't support transform rotation

### ISSUE THREAD

**Issue by Goktug** [ChiliLabs/CHIPageControl#39]
First of all, thanks for the marvelous package. I wanted to use the `Jalapeno` package as a vertical page control. For that reason, I applied the transform which is `pageControl.transform.rotated(by: .pi/2)` to the view and then I used auto layout for positioning but it didn't work as expected.

Can you fix this issue?

**Comment by chili-ios** [comment]
Hi @Goktug ,

Yeah, that's the only page control that has this bug :) will be fixed in next update.
Thanks for bug report.
