### ISSUE TITLE
missing cleanup for CADisplayLink

### ISSUE THREAD

**Issue by RolandasRazma** [ChiliLabs/CHIPageControl#40]
Correct me if I'm wrong but aren't you missing cleanup for `CADisplayLink`? 
Shouldn't you at least `.invalidate()` it (probably remove from runloop also) before `CHIBasePageControl` is deallocated? Otherwise you risking of calling method on deallocated `CHIBasePageControl`

**Comment by chili-ios** [comment]
hi @RolandasRazma ,
You are absolutely right. I'm going to fix it in next update. 
Thank you for a bug report.

**Comment by RolandasRazma** [comment]
thanks
