### ISSUE TITLE
Code signing issue

### ISSUE THREAD

**Issue by hsncr** [ChiliLabs/CHIPageControl#47]
I have following error on my storyboard that breaks the view for view controller that I've used page control. it shows all my views as white blank views on the storyboard for related view controller.

> Profile.storyboard: error: IB Designables: Failed to render and update auto layout status for ProfileDetailController (mG7-Ex-hLd): dlopen(CHIPageControl.framework, 1): no suitable image found.  Did find:
> 	CHIPageControl.framework: required code signature missing for 'CHIPageControl.framework'

What should I do to fix it? it is so annoying. I am using latest version.

**Comment by viennhn** [comment]
You need add code bellow to podfile
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
  end

**Comment by hsncr** [comment]
@viennhn thanks for the lead.

following comment has worked.
https://github.com/CocoaPods/CocoaPods/issues/3198#issuecomment-131115253
