### ISSUE TITLE
It will be good to have name of each class below animation

### ISSUE THREAD

**Issue by castus** [ChiliLabs/CHIPageControl#5]
It will be good to have name of each class below animation that you have on github README.md. 
Now I need to run every single class to check what effect it produces ;)

Thanks, KR

**Comment by chili-ios** [comment]
@castus , yes good idea :) will update Readme with some fixes during the weekend

**Comment by chili-ios** [comment]
@castus, Readme updated with version 0.0.2

**Comment by castus** [comment]
@chili-ios Great work, thanks 👏
