### ISSUE TITLE
Unable to build project on pod update

### ISSUE THREAD

**Issue by pranita-mindstix** [ChiliLabs/CHIPageControl#51]
I have updated "CHIPageControl" pod to latest version '0.1.7'. On building the project I am getting error - "Type 'RunLoopMode' has no member 'common'"

PFA for the error screenshot.
<img width="1280" alt="error" src="https://user-images.githubusercontent.com/8039894/45870978-e0984b80-bda9-11e8-8ee2-4b57eb3a2918.png">

**Comment by chili-ios** [comment]
Hi @pranita-mindstix ,

v 0.1.7 was updated to swift 4.2. Please use v 0.1.6 instead.

**Comment by pranita-mindstix** [comment]
Ok Thanks for quick reply!
