### ISSUE TITLE
Unrecognized Selector

### ISSUE THREAD

**Issue by papipons** [ChiliLabs/CHIPageControl#52]
Has crashing issues in v0.1.7 using swift 4.2

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CHIPageControl.WeakProxy updateFrame]: unrecognized selector sent to instance 0x1c4014240
```

**Comment by markcdb** [comment]
+1 for this

**Comment by aaronmusa** [comment]
up

**Comment by Powersel** [comment]
Same problem. Unfortunately, issue has random origin. Key point it's to show CHILPageControl item on screen and work with it, after, when I release (navigation stack) this screen crash can appears at any time.

**Comment by Powersel** [comment]
PS. Extra info, in my project any entity of CHIPageControlChimayo doesent deallocated. Both options, if UI element created as outlet or programmatically.

**Comment by chili-ios** [comment]
hey @Powersel ,
Does your viewcontroller deallocate? I've made some tests in demo project even with CHIPageControlChimayo and everything works as expected and pageControl gets deallocated.

**Comment by Powersel** [comment]
@chili-ios Hello, yep, all UI elements at top layer are trying to dealloc. In my case UICollectionCell trys to dealloc, calls deinit func and at this time my custom subclass ( parental class is CHIPageControlChimayo) are creates this error.

**Comment by chili-ios** [comment]
@Powersel, 
Can you please a code example? 
I've tried to make a subclass of CHIPageControlChimayo and it deallocates as expected when viewcontroller deallocates.

**Comment by Powersel** [comment]
@chili-ios Can we move to Skype, Hangouts, Slack? It will be more comfortable.

**Comment by chili-ios** [comment]
@Powersel,
My skype - igors.nemenonoks

**Comment by chili-ios** [comment]
We have investigated the issue and can’t reproduce it. Could anyone help with the scenario? Seems like it’s a retain cycle or something like that.

**Comment by SatbirTanda** [comment]
+1 I am seeing this too `-[CHIPageControl.WeakProxy updateFrame]: unrecognized selector sent to instance 0x282a3d0e0`

**Comment by chili-ios** [comment]
We still need a working example of this bug. It seems that you have a retain cycle or something similar.

**Comment by SatbirTanda** [comment]
I solved this by commenting out 
```swift
    internal func setupDisplayLink() {
//        self.displayLink = CADisplayLink(target: WeakProxy(self), selector: #selector(updateFrame))
//        self.displayLink?.add(to: .current, forMode: .common)
    }

//    @objc internal func updateFrame() {
//        self.animate()
//    }
```

**Comment by papipons** [comment]
Can't replicate the issue anymore. Closing this issue.
