### ISSUE TITLE
SPM Support Not Working

### ISSUE THREAD

**Issue by Cydie** [ChiliLabs/CHIPageControl#80]
The package has been updated recently with SPM support (#79 and #78), but I get errors with it.

I am on Xcode 13.0, using the built in Swift Package Manager, and specify the master branch in rules when adding the package.

When I import the module in my code, I receive the error 
`"No such module 'CHIPageControl'"`

Additionally, I receive a warning which might be related

`found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
/Users/******/Library/Developer/Xcode/DerivedData/*****-aheljstdlofofhcbswicoezhhaqd/SourcePackages/checkouts/CHIPageControl/CHIPageControl/Info.plist`

**Comment by chili-ios** [comment]
Hi @Cydie ,
Could you try now, please? I have published a new release.

**Comment by BigDada1** [comment]
Still won't working with v0.2.1 … 😞

**Comment by BigDada1** [comment]
Hi @chili-ios ,
other libraries fixed the warning by explicitly [excluding the resource file](https://github.com/aws-amplify/amplify-ios/commit/c659a2653caa6351eb578dd7b8defa92af701835). Could You try it, please?

**Comment by SerhanAksut** [comment]
Could you please try it with this PR https://github.com/ChiliLabs/CHIPageControl/pull/81

Because it's working as expected for me and I'm using Xcode13.1

I've also fixed this warning 👇 that you mentioned.

```found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target /Users/******/Library/Developer/Xcode/DerivedData/*****-aheljstdlofofhcbswicoezhhaqd/SourcePackages/checkouts/CHIPageControl/CHIPageControl/Info.plist```

Also, this is warning, not an error. It's resolved now with the PR https://github.com/ChiliLabs/CHIPageControl/pull/81

**Comment by chili-ios** [comment]
PR #81 is merged. Guys, please check if everything is working properly now.

**Comment by BigDada1** [comment]
Works like a charme 🙌🏻 … sry for the late response
